CREATE TABLE stock
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64)   NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(64),
    PRICE DECIMAL(15, 2) NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP,
    VERSION INT NOT NULL DEFAULT 0
);