CREATE TABLE stock_exchange
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(64)   NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(64),
    LIVE_IN_MARKET BOOLEAN DEFAULT FALSE,
    CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP,
    VERSION INT NOT NULL DEFAULT 0
);